replicaCount: 1

image:
  repository: qdrant/qdrant
  pullPolicy: IfNotPresent
  tag: v0.8.2

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# checks - Readiness and liveness checks can only be enabled for either rest or grpc (multiple checks not supported)
# grpc checks are only available from k8s 1.24+ so as of per default we check rest
service:
  type: ClusterIP
  ports:
    - name: rest
      port: 6333
      targetPort: 6333
      protocol: TCP
      checksEnabled: true
    - name: grpc
      port: 6334
      targetPort: 6334
      protocol: TCP
      checksEnabled: false
    - name: p2p
      port: 6335
      targetPort: 6335
      protocol: TCP
      checksEnabled: false

livenessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1

podAnnotations: {}

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  accessModes: [ "ReadWriteOnce" ]  
  size: 1Gi
  #storageClassName: local-path

config:
  debug: false
  log_level: INFO
  storage:
    storage_path: ./storage
    wal:
      wal_capacity_mb: 32
      wal_segments_ahead: 0
    performance:
      max_search_threads: 0
    optimizers:
      deleted_threshold: 0.2
      vacuum_min_vector_number: 1000
      default_segment_number: 5
      max_segment_size: 200000
      memmap_threshold: 50000
      indexing_threshold: 20000
      payload_indexing_threshold: 10000
      flush_interval_sec: 1
      max_optimization_threads: 0
    hnsw_index:
      m: 16
      ef_construct: 100
      full_scan_threshold: 10000
  service:
    max_request_size_mb: 32
    max_workers: 0
    host: 0.0.0.0
    http_port: 6333
    grpc_port: 6334
    enable_cors: true
  cluster:
    enabled: false
    p2p:
      port: 6335
    consensus:
      tick_period_ms: 100
