replicaCount: 1

image:
  repository: qdrant/qdrant
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

ports:
  - name: http
    containerPort: 6333
    protocol: TCP

livenessProbe:
  enabled: true
  path: /
  port: 6333
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  enabled: true
  path: /
  port: 6333
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1

podAnnotations: {}

service:
  type: ClusterIP
  name: http
  port: 6333
  targetPort: 6333

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  accessModes: [ "ReadWriteOnce" ]  
  size: 1Gi
